service: minimal-example

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1


functions:
  validateIsin:
    handler: ./v1/foo/bar/handler.hello
    events:
      - http:
          path: /
          method: get
  nolog:
    handler: ./v1/foo/nolog/handler.hello
    events:
      - http:
          path: /nolog
          method: get
